// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gt-conf-pb/gs-mysql-pb.proto

package gtconfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// mysql配置
type MysqlConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Con           *MysqlConnectConfig    `protobuf:"bytes,1,opt,name=con,proto3" json:"con,omitempty"`                       // mysql连接配置
	MaxOpenCon    *uint32                `protobuf:"varint,2,opt,name=maxOpenCon,proto3,oneof" json:"maxOpenCon,omitempty"`  // 最大数据库连接数（默认 10 * CPU 核数）
	MaxIdleCon    *uint32                `protobuf:"varint,3,opt,name=maxIdleCon,proto3,oneof" json:"maxIdleCon,omitempty"`  // 最大数据库等待连接数（默认为 2）
	MaxIdleTime   *durationpb.Duration   `protobuf:"bytes,4,opt,name=maxIdleTime,proto3,oneof" json:"maxIdleTime,omitempty"` // 最大连接池等待时间（默认为 0，取决于连接空闲时间）
	MaxLifeTime   *durationpb.Duration   `protobuf:"bytes,5,opt,name=maxLifeTime,proto3,oneof" json:"maxLifeTime,omitempty"` // 最大连接池生命周期（默认为 0，取决于连接过期时间）
	PingTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=pingTimeout,proto3,oneof" json:"pingTimeout,omitempty"` // ping超时时间（默认 1 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlConfig) Reset() {
	*x = MysqlConfig{}
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlConfig) ProtoMessage() {}

func (x *MysqlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlConfig.ProtoReflect.Descriptor instead.
func (*MysqlConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_mysql_pb_proto_rawDescGZIP(), []int{0}
}

func (x *MysqlConfig) GetCon() *MysqlConnectConfig {
	if x != nil {
		return x.Con
	}
	return nil
}

func (x *MysqlConfig) GetMaxOpenCon() uint32 {
	if x != nil && x.MaxOpenCon != nil {
		return *x.MaxOpenCon
	}
	return 0
}

func (x *MysqlConfig) GetMaxIdleCon() uint32 {
	if x != nil && x.MaxIdleCon != nil {
		return *x.MaxIdleCon
	}
	return 0
}

func (x *MysqlConfig) GetMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxIdleTime
	}
	return nil
}

func (x *MysqlConfig) GetMaxLifeTime() *durationpb.Duration {
	if x != nil {
		return x.MaxLifeTime
	}
	return nil
}

func (x *MysqlConfig) GetPingTimeout() *durationpb.Duration {
	if x != nil {
		return x.PingTimeout
	}
	return nil
}

// mysql 连接配置
type MysqlConnectConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`                                                                                    // dsn, 格式为 [username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN], 若非空则其余字段失效
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                                                                                      // IP，必填
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                                                                 // 端口，必填
	UserName      string                 `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`                                                                          // 用户名，必填
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                                                                          // 密码，必填
	DbName        string                 `protobuf:"bytes,6,opt,name=dbName,proto3" json:"dbName,omitempty"`                                                                              // 库名，必填
	Network       *string                `protobuf:"bytes,7,opt,name=network,proto3,oneof" json:"network,omitempty"`                                                                      // 网络协议类型, tcp/udp, 不填默认tcp
	Charset       *string                `protobuf:"bytes,8,opt,name=charset,proto3,oneof" json:"charset,omitempty"`                                                                      // 字符集。不填默认utf8mb4
	DontParseTime bool                   `protobuf:"varint,9,opt,name=dontParseTime,proto3" json:"dontParseTime,omitempty"`                                                               // 不数据库时间转换成golang.Time.Time。默认false。
	Location      *string                `protobuf:"bytes,10,opt,name=location,proto3,oneof" json:"location,omitempty"`                                                                   // 解析时间类型时的时区(不影响实际存储的数据时区), 不填默认UTC。中国地区: Asia%2FShanghai
	Options       map[string]string      `protobuf:"bytes,11,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 其他连接参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlConnectConfig) Reset() {
	*x = MysqlConnectConfig{}
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlConnectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlConnectConfig) ProtoMessage() {}

func (x *MysqlConnectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlConnectConfig.ProtoReflect.Descriptor instead.
func (*MysqlConnectConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_mysql_pb_proto_rawDescGZIP(), []int{1}
}

func (x *MysqlConnectConfig) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *MysqlConnectConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MysqlConnectConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MysqlConnectConfig) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MysqlConnectConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MysqlConnectConfig) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *MysqlConnectConfig) GetNetwork() string {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return ""
}

func (x *MysqlConnectConfig) GetCharset() string {
	if x != nil && x.Charset != nil {
		return *x.Charset
	}
	return ""
}

func (x *MysqlConnectConfig) GetDontParseTime() bool {
	if x != nil {
		return x.DontParseTime
	}
	return false
}

func (x *MysqlConnectConfig) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *MysqlConnectConfig) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// mysql表结构定制化配置
type MysqlTableFieldCustomizedConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`   // 定制化字段(无需附带逗号) etc: "`cv_tag` BIGINT(20) UNSIGNED AS (json_unquote(json_extract(`du_device_core_info`,_utf8mb4\'$.CvTag\'))) stored"
	Indexes       []string               `protobuf:"bytes,2,rep,name=indexes,proto3" json:"indexes,omitempty"` // 定制化索引(无需附带逗号) etc: "INDEX `idx_cv_tag` (`cv_tag`) USING BTREE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlTableFieldCustomizedConfig) Reset() {
	*x = MysqlTableFieldCustomizedConfig{}
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlTableFieldCustomizedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlTableFieldCustomizedConfig) ProtoMessage() {}

func (x *MysqlTableFieldCustomizedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlTableFieldCustomizedConfig.ProtoReflect.Descriptor instead.
func (*MysqlTableFieldCustomizedConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_mysql_pb_proto_rawDescGZIP(), []int{2}
}

func (x *MysqlTableFieldCustomizedConfig) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MysqlTableFieldCustomizedConfig) GetIndexes() []string {
	if x != nil {
		return x.Indexes
	}
	return nil
}

var File_gt_conf_pb_gs_mysql_pb_proto protoreflect.FileDescriptor

const file_gt_conf_pb_gs_mysql_pb_proto_rawDesc = "" +
	"\n" +
	"\x1cgt-conf-pb/gs-mysql-pb.proto\x12\bgtconfpb\x1a\x1egoogle/protobuf/duration.proto\"\x9b\x03\n" +
	"\vMysqlConfig\x12.\n" +
	"\x03con\x18\x01 \x01(\v2\x1c.gtconfpb.MysqlConnectConfigR\x03con\x12#\n" +
	"\n" +
	"maxOpenCon\x18\x02 \x01(\rH\x00R\n" +
	"maxOpenCon\x88\x01\x01\x12#\n" +
	"\n" +
	"maxIdleCon\x18\x03 \x01(\rH\x01R\n" +
	"maxIdleCon\x88\x01\x01\x12@\n" +
	"\vmaxIdleTime\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x02R\vmaxIdleTime\x88\x01\x01\x12@\n" +
	"\vmaxLifeTime\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x03R\vmaxLifeTime\x88\x01\x01\x12@\n" +
	"\vpingTimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x04R\vpingTimeout\x88\x01\x01B\r\n" +
	"\v_maxOpenConB\r\n" +
	"\v_maxIdleConB\x0e\n" +
	"\f_maxIdleTimeB\x0e\n" +
	"\f_maxLifeTimeB\x0e\n" +
	"\f_pingTimeout\"\xc5\x03\n" +
	"\x12MysqlConnectConfig\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\buserName\x18\x04 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x16\n" +
	"\x06dbName\x18\x06 \x01(\tR\x06dbName\x12\x1d\n" +
	"\anetwork\x18\a \x01(\tH\x00R\anetwork\x88\x01\x01\x12\x1d\n" +
	"\acharset\x18\b \x01(\tH\x01R\acharset\x88\x01\x01\x12$\n" +
	"\rdontParseTime\x18\t \x01(\bR\rdontParseTime\x12\x1f\n" +
	"\blocation\x18\n" +
	" \x01(\tH\x02R\blocation\x88\x01\x01\x12C\n" +
	"\aoptions\x18\v \x03(\v2).gtconfpb.MysqlConnectConfig.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_networkB\n" +
	"\n" +
	"\b_charsetB\v\n" +
	"\t_location\"S\n" +
	"\x1fMysqlTableFieldCustomizedConfig\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x18\n" +
	"\aindexes\x18\x02 \x03(\tR\aindexesB;Z9github.com/DontBeProud/go-treasure/pb/gt-conf-pb;gtconfpbb\x06proto3"

var (
	file_gt_conf_pb_gs_mysql_pb_proto_rawDescOnce sync.Once
	file_gt_conf_pb_gs_mysql_pb_proto_rawDescData []byte
)

func file_gt_conf_pb_gs_mysql_pb_proto_rawDescGZIP() []byte {
	file_gt_conf_pb_gs_mysql_pb_proto_rawDescOnce.Do(func() {
		file_gt_conf_pb_gs_mysql_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_mysql_pb_proto_rawDesc), len(file_gt_conf_pb_gs_mysql_pb_proto_rawDesc)))
	})
	return file_gt_conf_pb_gs_mysql_pb_proto_rawDescData
}

var file_gt_conf_pb_gs_mysql_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gt_conf_pb_gs_mysql_pb_proto_goTypes = []any{
	(*MysqlConfig)(nil),                     // 0: gtconfpb.MysqlConfig
	(*MysqlConnectConfig)(nil),              // 1: gtconfpb.MysqlConnectConfig
	(*MysqlTableFieldCustomizedConfig)(nil), // 2: gtconfpb.MysqlTableFieldCustomizedConfig
	nil,                                     // 3: gtconfpb.MysqlConnectConfig.OptionsEntry
	(*durationpb.Duration)(nil),             // 4: google.protobuf.Duration
}
var file_gt_conf_pb_gs_mysql_pb_proto_depIdxs = []int32{
	1, // 0: gtconfpb.MysqlConfig.con:type_name -> gtconfpb.MysqlConnectConfig
	4, // 1: gtconfpb.MysqlConfig.maxIdleTime:type_name -> google.protobuf.Duration
	4, // 2: gtconfpb.MysqlConfig.maxLifeTime:type_name -> google.protobuf.Duration
	4, // 3: gtconfpb.MysqlConfig.pingTimeout:type_name -> google.protobuf.Duration
	3, // 4: gtconfpb.MysqlConnectConfig.options:type_name -> gtconfpb.MysqlConnectConfig.OptionsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gt_conf_pb_gs_mysql_pb_proto_init() }
func file_gt_conf_pb_gs_mysql_pb_proto_init() {
	if File_gt_conf_pb_gs_mysql_pb_proto != nil {
		return
	}
	file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[0].OneofWrappers = []any{}
	file_gt_conf_pb_gs_mysql_pb_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_mysql_pb_proto_rawDesc), len(file_gt_conf_pb_gs_mysql_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gt_conf_pb_gs_mysql_pb_proto_goTypes,
		DependencyIndexes: file_gt_conf_pb_gs_mysql_pb_proto_depIdxs,
		MessageInfos:      file_gt_conf_pb_gs_mysql_pb_proto_msgTypes,
	}.Build()
	File_gt_conf_pb_gs_mysql_pb_proto = out.File
	file_gt_conf_pb_gs_mysql_pb_proto_goTypes = nil
	file_gt_conf_pb_gs_mysql_pb_proto_depIdxs = nil
}
