// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gt-conf-pb/gs-nacos-pb.proto

package gtconfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// nacos 配置
type NacosConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      []string               `protobuf:"bytes,1,rep,name=endpoint,proto3" json:"endpoint,omitempty"`       // 终端地址。例: ["127.0.0.1:8848", "192.168.243.243"], 默认端口8848
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`     // 命名空间
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`       // 用户名
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`       // 密码
	AccessKey     string                 `protobuf:"bytes,5,opt,name=accessKey,proto3" json:"accessKey,omitempty"`     // the AccessKey for kms 如果同时配置了 ak/sk 则用户名/密码失效
	SecretKey     string                 `protobuf:"bytes,6,opt,name=secretKey,proto3" json:"secretKey,omitempty"`     // the SecretKey for kms 如果同时配置了 ak/sk 则用户名/密码失效
	LogDir        *string                `protobuf:"bytes,7,opt,name=logDir,proto3,oneof" json:"logDir,omitempty"`     // 日志目录，默认为 /tmp/nacos/log
	CacheDir      *string                `protobuf:"bytes,8,opt,name=cacheDir,proto3,oneof" json:"cacheDir,omitempty"` // 缓存目录，默认为 /tmp/nacos/cache
	Timeout       *durationpb.Duration   `protobuf:"bytes,9,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`   // 客户端连接超时时间（单位毫秒），默认 10s
	RegionID      string                 `protobuf:"bytes,10,opt,name=regionID,proto3" json:"regionID,omitempty"`      // region ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NacosConfig) Reset() {
	*x = NacosConfig{}
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NacosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosConfig) ProtoMessage() {}

func (x *NacosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosConfig.ProtoReflect.Descriptor instead.
func (*NacosConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_nacos_pb_proto_rawDescGZIP(), []int{0}
}

func (x *NacosConfig) GetEndpoint() []string {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *NacosConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NacosConfig) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *NacosConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NacosConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *NacosConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *NacosConfig) GetLogDir() string {
	if x != nil && x.LogDir != nil {
		return *x.LogDir
	}
	return ""
}

func (x *NacosConfig) GetCacheDir() string {
	if x != nil && x.CacheDir != nil {
		return *x.CacheDir
	}
	return ""
}

func (x *NacosConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *NacosConfig) GetRegionID() string {
	if x != nil {
		return x.RegionID
	}
	return ""
}

// nacos注册中心配置
type NacosRegistryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`     // 分组
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`   // 前缀
	Weight        float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"` // 权重
	Cluster       string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"` // 集群名称
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`       // kind
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NacosRegistryConfig) Reset() {
	*x = NacosRegistryConfig{}
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NacosRegistryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosRegistryConfig) ProtoMessage() {}

func (x *NacosRegistryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosRegistryConfig.ProtoReflect.Descriptor instead.
func (*NacosRegistryConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_nacos_pb_proto_rawDescGZIP(), []int{1}
}

func (x *NacosRegistryConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NacosRegistryConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *NacosRegistryConfig) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NacosRegistryConfig) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *NacosRegistryConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// nacos数据中心配置
type NacosConfigCenterConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataId           string                 `protobuf:"bytes,1,opt,name=dataId,proto3" json:"dataId,omitempty"`                      // 配置文件名称
	Group            string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`                        // 配置文件分组
	Tag              string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`                            // 配置文件标签
	ConfigTags       string                 `protobuf:"bytes,4,opt,name=configTags,proto3" json:"configTags,omitempty"`              // 配置文件标签
	AppName          string                 `protobuf:"bytes,5,opt,name=appName,proto3" json:"appName,omitempty"`                    // 应用名称
	BetaIps          string                 `protobuf:"bytes,6,opt,name=betaIps,proto3" json:"betaIps,omitempty"`                    // beta ip
	CasMd5           string                 `protobuf:"bytes,7,opt,name=casMd5,proto3" json:"casMd5,omitempty"`                      // 配置文件的 MD5 值
	Type             string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`                          // 配置文件类型
	SrcUser          string                 `protobuf:"bytes,9,opt,name=srcUser,proto3" json:"srcUser,omitempty"`                    // 来源用户
	EncryptedDataKey string                 `protobuf:"bytes,10,opt,name=encryptedDataKey,proto3" json:"encryptedDataKey,omitempty"` // 加密数据密钥
	KmsKeyId         string                 `protobuf:"bytes,11,opt,name=kmsKeyId,proto3" json:"kmsKeyId,omitempty"`                 // KMS 密钥 ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NacosConfigCenterConfig) Reset() {
	*x = NacosConfigCenterConfig{}
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NacosConfigCenterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosConfigCenterConfig) ProtoMessage() {}

func (x *NacosConfigCenterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosConfigCenterConfig.ProtoReflect.Descriptor instead.
func (*NacosConfigCenterConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_nacos_pb_proto_rawDescGZIP(), []int{2}
}

func (x *NacosConfigCenterConfig) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetConfigTags() string {
	if x != nil {
		return x.ConfigTags
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetBetaIps() string {
	if x != nil {
		return x.BetaIps
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetCasMd5() string {
	if x != nil {
		return x.CasMd5
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetSrcUser() string {
	if x != nil {
		return x.SrcUser
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetEncryptedDataKey() string {
	if x != nil {
		return x.EncryptedDataKey
	}
	return ""
}

func (x *NacosConfigCenterConfig) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

var File_gt_conf_pb_gs_nacos_pb_proto protoreflect.FileDescriptor

const file_gt_conf_pb_gs_nacos_pb_proto_rawDesc = "" +
	"\n" +
	"\x1cgt-conf-pb/gs-nacos-pb.proto\x12\bgtconfpb\x1a\x1egoogle/protobuf/duration.proto\"\xf3\x02\n" +
	"\vNacosConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x03(\tR\bendpoint\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\taccessKey\x18\x05 \x01(\tR\taccessKey\x12\x1c\n" +
	"\tsecretKey\x18\x06 \x01(\tR\tsecretKey\x12\x1b\n" +
	"\x06logDir\x18\a \x01(\tH\x00R\x06logDir\x88\x01\x01\x12\x1f\n" +
	"\bcacheDir\x18\b \x01(\tH\x01R\bcacheDir\x88\x01\x01\x128\n" +
	"\atimeout\x18\t \x01(\v2\x19.google.protobuf.DurationH\x02R\atimeout\x88\x01\x01\x12\x1a\n" +
	"\bregionID\x18\n" +
	" \x01(\tR\bregionIDB\t\n" +
	"\a_logDirB\v\n" +
	"\t_cacheDirB\n" +
	"\n" +
	"\b_timeout\"\x89\x01\n" +
	"\x13NacosRegistryConfig\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x02R\x06weight\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"\xbb\x02\n" +
	"\x17NacosConfigCenterConfig\x12\x16\n" +
	"\x06dataId\x18\x01 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"configTags\x18\x04 \x01(\tR\n" +
	"configTags\x12\x18\n" +
	"\aappName\x18\x05 \x01(\tR\aappName\x12\x18\n" +
	"\abetaIps\x18\x06 \x01(\tR\abetaIps\x12\x16\n" +
	"\x06casMd5\x18\a \x01(\tR\x06casMd5\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x18\n" +
	"\asrcUser\x18\t \x01(\tR\asrcUser\x12*\n" +
	"\x10encryptedDataKey\x18\n" +
	" \x01(\tR\x10encryptedDataKey\x12\x1a\n" +
	"\bkmsKeyId\x18\v \x01(\tR\bkmsKeyIdB;Z9github.com/DontBeProud/go-treasure/pb/gt-conf-pb;gtconfpbb\x06proto3"

var (
	file_gt_conf_pb_gs_nacos_pb_proto_rawDescOnce sync.Once
	file_gt_conf_pb_gs_nacos_pb_proto_rawDescData []byte
)

func file_gt_conf_pb_gs_nacos_pb_proto_rawDescGZIP() []byte {
	file_gt_conf_pb_gs_nacos_pb_proto_rawDescOnce.Do(func() {
		file_gt_conf_pb_gs_nacos_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_nacos_pb_proto_rawDesc), len(file_gt_conf_pb_gs_nacos_pb_proto_rawDesc)))
	})
	return file_gt_conf_pb_gs_nacos_pb_proto_rawDescData
}

var file_gt_conf_pb_gs_nacos_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gt_conf_pb_gs_nacos_pb_proto_goTypes = []any{
	(*NacosConfig)(nil),             // 0: gtconfpb.NacosConfig
	(*NacosRegistryConfig)(nil),     // 1: gtconfpb.NacosRegistryConfig
	(*NacosConfigCenterConfig)(nil), // 2: gtconfpb.NacosConfigCenterConfig
	(*durationpb.Duration)(nil),     // 3: google.protobuf.Duration
}
var file_gt_conf_pb_gs_nacos_pb_proto_depIdxs = []int32{
	3, // 0: gtconfpb.NacosConfig.timeout:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gt_conf_pb_gs_nacos_pb_proto_init() }
func file_gt_conf_pb_gs_nacos_pb_proto_init() {
	if File_gt_conf_pb_gs_nacos_pb_proto != nil {
		return
	}
	file_gt_conf_pb_gs_nacos_pb_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_nacos_pb_proto_rawDesc), len(file_gt_conf_pb_gs_nacos_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gt_conf_pb_gs_nacos_pb_proto_goTypes,
		DependencyIndexes: file_gt_conf_pb_gs_nacos_pb_proto_depIdxs,
		MessageInfos:      file_gt_conf_pb_gs_nacos_pb_proto_msgTypes,
	}.Build()
	File_gt_conf_pb_gs_nacos_pb_proto = out.File
	file_gt_conf_pb_gs_nacos_pb_proto_goTypes = nil
	file_gt_conf_pb_gs_nacos_pb_proto_depIdxs = nil
}
