// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gt-conf-pb/gs-redis-pb.proto

package gtconfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// redis 配置
type RedisConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Con             *RedisConnectConfig    `protobuf:"bytes,1,opt,name=con,proto3" json:"con,omitempty"`                          // 连接配置
	MasterName      string                 `protobuf:"bytes,2,opt,name=masterName,proto3" json:"masterName,omitempty"`            // 哨兵模式的 master name
	Db              uint32                 `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`                           // db，默认0
	DisableReadOnly bool                   `protobuf:"varint,4,opt,name=disableReadOnly,proto3" json:"disableReadOnly,omitempty"` // 禁用从节点读
	RouteRandomly   bool                   `protobuf:"varint,5,opt,name=routeRandomly,proto3" json:"routeRandomly,omitempty"`     // 随机路由
	RouteByLatency  bool                   `protobuf:"varint,6,opt,name=routeByLatency,proto3" json:"routeByLatency,omitempty"`   // 根据延迟路由
	DialTimeout     *durationpb.Duration   `protobuf:"bytes,7,opt,name=dialTimeout,proto3,oneof" json:"dialTimeout,omitempty"`    // 连接超时时间（默认 5 秒）
	ReadTimeout     *durationpb.Duration   `protobuf:"bytes,8,opt,name=readTimeout,proto3,oneof" json:"readTimeout,omitempty"`    // 读超时时间（默认 3 秒）
	WriteTimeout    *durationpb.Duration   `protobuf:"bytes,9,opt,name=writeTimeout,proto3,oneof" json:"writeTimeout,omitempty"`  // 写超时时间（默认等于读超时时间）
	PoolSize        *uint32                `protobuf:"varint,10,opt,name=poolSize,proto3,oneof" json:"poolSize,omitempty"`        // 最大连接池数（默认 10 * CPU 核数）
	MinIdleCons     uint32                 `protobuf:"varint,11,opt,name=minIdleCons,proto3" json:"minIdleCons,omitempty"`        // 最小空闲连接数（默认为 0）
	MaxConAge       *durationpb.Duration   `protobuf:"bytes,12,opt,name=maxConAge,proto3,oneof" json:"maxConAge,omitempty"`       // 最大过期时间（默认为 0 不过期）
	PoolTimeout     *durationpb.Duration   `protobuf:"bytes,13,opt,name=poolTimeout,proto3,oneof" json:"poolTimeout,omitempty"`   // 连接池超时时间（默认读超时时间 +1 秒）
	IdleTimeout     *durationpb.Duration   `protobuf:"bytes,14,opt,name=idleTimeout,proto3,oneof" json:"idleTimeout,omitempty"`   // 空闲超时时间（默认 5 分钟，设置 -1 可关闭空闲检查）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedisConfig) Reset() {
	*x = RedisConfig{}
	mi := &file_gt_conf_pb_gs_redis_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConfig) ProtoMessage() {}

func (x *RedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_redis_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConfig.ProtoReflect.Descriptor instead.
func (*RedisConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_redis_pb_proto_rawDescGZIP(), []int{0}
}

func (x *RedisConfig) GetCon() *RedisConnectConfig {
	if x != nil {
		return x.Con
	}
	return nil
}

func (x *RedisConfig) GetMasterName() string {
	if x != nil {
		return x.MasterName
	}
	return ""
}

func (x *RedisConfig) GetDb() uint32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *RedisConfig) GetDisableReadOnly() bool {
	if x != nil {
		return x.DisableReadOnly
	}
	return false
}

func (x *RedisConfig) GetRouteRandomly() bool {
	if x != nil {
		return x.RouteRandomly
	}
	return false
}

func (x *RedisConfig) GetRouteByLatency() bool {
	if x != nil {
		return x.RouteByLatency
	}
	return false
}

func (x *RedisConfig) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *RedisConfig) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *RedisConfig) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *RedisConfig) GetPoolSize() uint32 {
	if x != nil && x.PoolSize != nil {
		return *x.PoolSize
	}
	return 0
}

func (x *RedisConfig) GetMinIdleCons() uint32 {
	if x != nil {
		return x.MinIdleCons
	}
	return 0
}

func (x *RedisConfig) GetMaxConAge() *durationpb.Duration {
	if x != nil {
		return x.MaxConAge
	}
	return nil
}

func (x *RedisConfig) GetPoolTimeout() *durationpb.Duration {
	if x != nil {
		return x.PoolTimeout
	}
	return nil
}

func (x *RedisConfig) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

// redis 连接配置
type RedisConnectConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Addr             string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                         // addr host:port（默认为 127.0.0.1:6379）
	ClusterAddr      []string               `protobuf:"bytes,2,rep,name=clusterAddr,proto3" json:"clusterAddr,omitempty"`           // clusterAddr host:port
	UserName         string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`                 // 用户名
	Password         string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                 // 密码
	SentinelUserName string                 `protobuf:"bytes,5,opt,name=sentinelUserName,proto3" json:"sentinelUserName,omitempty"` // 哨兵用户名
	SentinelPassword string                 `protobuf:"bytes,6,opt,name=sentinelPassword,proto3" json:"sentinelPassword,omitempty"` // 哨兵密码
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RedisConnectConfig) Reset() {
	*x = RedisConnectConfig{}
	mi := &file_gt_conf_pb_gs_redis_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisConnectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConnectConfig) ProtoMessage() {}

func (x *RedisConnectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gs_redis_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConnectConfig.ProtoReflect.Descriptor instead.
func (*RedisConnectConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gs_redis_pb_proto_rawDescGZIP(), []int{1}
}

func (x *RedisConnectConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedisConnectConfig) GetClusterAddr() []string {
	if x != nil {
		return x.ClusterAddr
	}
	return nil
}

func (x *RedisConnectConfig) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RedisConnectConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisConnectConfig) GetSentinelUserName() string {
	if x != nil {
		return x.SentinelUserName
	}
	return ""
}

func (x *RedisConnectConfig) GetSentinelPassword() string {
	if x != nil {
		return x.SentinelPassword
	}
	return ""
}

var File_gt_conf_pb_gs_redis_pb_proto protoreflect.FileDescriptor

const file_gt_conf_pb_gs_redis_pb_proto_rawDesc = "" +
	"\n" +
	"\x1cgt-conf-pb/gs-redis-pb.proto\x12\bgtconfpb\x1a\x1egoogle/protobuf/duration.proto\"\x9e\x06\n" +
	"\vRedisConfig\x12.\n" +
	"\x03con\x18\x01 \x01(\v2\x1c.gtconfpb.RedisConnectConfigR\x03con\x12\x1e\n" +
	"\n" +
	"masterName\x18\x02 \x01(\tR\n" +
	"masterName\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\rR\x02db\x12(\n" +
	"\x0fdisableReadOnly\x18\x04 \x01(\bR\x0fdisableReadOnly\x12$\n" +
	"\rrouteRandomly\x18\x05 \x01(\bR\rrouteRandomly\x12&\n" +
	"\x0erouteByLatency\x18\x06 \x01(\bR\x0erouteByLatency\x12@\n" +
	"\vdialTimeout\x18\a \x01(\v2\x19.google.protobuf.DurationH\x00R\vdialTimeout\x88\x01\x01\x12@\n" +
	"\vreadTimeout\x18\b \x01(\v2\x19.google.protobuf.DurationH\x01R\vreadTimeout\x88\x01\x01\x12B\n" +
	"\fwriteTimeout\x18\t \x01(\v2\x19.google.protobuf.DurationH\x02R\fwriteTimeout\x88\x01\x01\x12\x1f\n" +
	"\bpoolSize\x18\n" +
	" \x01(\rH\x03R\bpoolSize\x88\x01\x01\x12 \n" +
	"\vminIdleCons\x18\v \x01(\rR\vminIdleCons\x12<\n" +
	"\tmaxConAge\x18\f \x01(\v2\x19.google.protobuf.DurationH\x04R\tmaxConAge\x88\x01\x01\x12@\n" +
	"\vpoolTimeout\x18\r \x01(\v2\x19.google.protobuf.DurationH\x05R\vpoolTimeout\x88\x01\x01\x12@\n" +
	"\vidleTimeout\x18\x0e \x01(\v2\x19.google.protobuf.DurationH\x06R\vidleTimeout\x88\x01\x01B\x0e\n" +
	"\f_dialTimeoutB\x0e\n" +
	"\f_readTimeoutB\x0f\n" +
	"\r_writeTimeoutB\v\n" +
	"\t_poolSizeB\f\n" +
	"\n" +
	"_maxConAgeB\x0e\n" +
	"\f_poolTimeoutB\x0e\n" +
	"\f_idleTimeout\"\xda\x01\n" +
	"\x12RedisConnectConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12 \n" +
	"\vclusterAddr\x18\x02 \x03(\tR\vclusterAddr\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12*\n" +
	"\x10sentinelUserName\x18\x05 \x01(\tR\x10sentinelUserName\x12*\n" +
	"\x10sentinelPassword\x18\x06 \x01(\tR\x10sentinelPasswordB;Z9github.com/DontBeProud/go-treasure/pb/gt-conf-pb;gtconfpbb\x06proto3"

var (
	file_gt_conf_pb_gs_redis_pb_proto_rawDescOnce sync.Once
	file_gt_conf_pb_gs_redis_pb_proto_rawDescData []byte
)

func file_gt_conf_pb_gs_redis_pb_proto_rawDescGZIP() []byte {
	file_gt_conf_pb_gs_redis_pb_proto_rawDescOnce.Do(func() {
		file_gt_conf_pb_gs_redis_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_redis_pb_proto_rawDesc), len(file_gt_conf_pb_gs_redis_pb_proto_rawDesc)))
	})
	return file_gt_conf_pb_gs_redis_pb_proto_rawDescData
}

var file_gt_conf_pb_gs_redis_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gt_conf_pb_gs_redis_pb_proto_goTypes = []any{
	(*RedisConfig)(nil),         // 0: gtconfpb.RedisConfig
	(*RedisConnectConfig)(nil),  // 1: gtconfpb.RedisConnectConfig
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_gt_conf_pb_gs_redis_pb_proto_depIdxs = []int32{
	1, // 0: gtconfpb.RedisConfig.con:type_name -> gtconfpb.RedisConnectConfig
	2, // 1: gtconfpb.RedisConfig.dialTimeout:type_name -> google.protobuf.Duration
	2, // 2: gtconfpb.RedisConfig.readTimeout:type_name -> google.protobuf.Duration
	2, // 3: gtconfpb.RedisConfig.writeTimeout:type_name -> google.protobuf.Duration
	2, // 4: gtconfpb.RedisConfig.maxConAge:type_name -> google.protobuf.Duration
	2, // 5: gtconfpb.RedisConfig.poolTimeout:type_name -> google.protobuf.Duration
	2, // 6: gtconfpb.RedisConfig.idleTimeout:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gt_conf_pb_gs_redis_pb_proto_init() }
func file_gt_conf_pb_gs_redis_pb_proto_init() {
	if File_gt_conf_pb_gs_redis_pb_proto != nil {
		return
	}
	file_gt_conf_pb_gs_redis_pb_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gs_redis_pb_proto_rawDesc), len(file_gt_conf_pb_gs_redis_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gt_conf_pb_gs_redis_pb_proto_goTypes,
		DependencyIndexes: file_gt_conf_pb_gs_redis_pb_proto_depIdxs,
		MessageInfos:      file_gt_conf_pb_gs_redis_pb_proto_msgTypes,
	}.Build()
	File_gt_conf_pb_gs_redis_pb_proto = out.File
	file_gt_conf_pb_gs_redis_pb_proto_goTypes = nil
	file_gt_conf_pb_gs_redis_pb_proto_depIdxs = nil
}
