// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gt-conf-pb/gt-logger-pb.proto

package gtconfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志级别
type LogLevel int32

const (
	LogLevel_debug LogLevel = 0
	LogLevel_info  LogLevel = 1
	LogLevel_warn  LogLevel = 2
	LogLevel_error LogLevel = 3
	LogLevel_fatal LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "debug",
		1: "info",
		2: "warn",
		3: "error",
		4: "fatal",
	}
	LogLevel_value = map[string]int32{
		"debug": 0,
		"info":  1,
		"warn":  2,
		"error": 3,
		"fatal": 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_gt_conf_pb_gt_logger_pb_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_gt_conf_pb_gt_logger_pb_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_logger_pb_proto_rawDescGZIP(), []int{0}
}

// 日志配置的proto
type LogConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DisableFileWriter bool                   `protobuf:"varint,1,opt,name=disableFileWriter,proto3" json:"disableFileWriter,omitempty"`      // 禁用日志文件写入
	DisableStdOut     bool                   `protobuf:"varint,2,opt,name=disableStdOut,proto3" json:"disableStdOut,omitempty"`              // 禁用std输出
	Dir               string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`                                   // 日志根目录
	RotationTime      *durationpb.Duration   `protobuf:"bytes,4,opt,name=rotationTime,proto3,oneof" json:"rotationTime,omitempty"`           // 日志滚动时间（默认为 1 小时）
	FileAge           *durationpb.Duration   `protobuf:"bytes,5,opt,name=fileAge,proto3,oneof" json:"fileAge,omitempty"`                     // 日志保存时间（默认为 180 天）
	LogLevel          LogLevel               `protobuf:"varint,6,opt,name=logLevel,proto3,enum=gtconfpb.LogLevel" json:"logLevel,omitempty"` // 日志最低输出等级（默认为 debug）
	ConstKv           []string               `protobuf:"bytes,7,rep,name=constKv,proto3" json:"constKv,omitempty"`                           // 固定输出的 key-value
	DisableJsonFmt    bool                   `protobuf:"varint,8,opt,name=disableJsonFmt,proto3" json:"disableJsonFmt,omitempty"`            // 是否禁用 json 格式输出（默认为 false）
	BeautyJsonFmt     bool                   `protobuf:"varint,9,opt,name=beautyJsonFmt,proto3" json:"beautyJsonFmt,omitempty"`              // 是否美化 json 格式输出（默认为 false）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_gt_conf_pb_gt_logger_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gt_logger_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_logger_pb_proto_rawDescGZIP(), []int{0}
}

func (x *LogConfig) GetDisableFileWriter() bool {
	if x != nil {
		return x.DisableFileWriter
	}
	return false
}

func (x *LogConfig) GetDisableStdOut() bool {
	if x != nil {
		return x.DisableStdOut
	}
	return false
}

func (x *LogConfig) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *LogConfig) GetRotationTime() *durationpb.Duration {
	if x != nil {
		return x.RotationTime
	}
	return nil
}

func (x *LogConfig) GetFileAge() *durationpb.Duration {
	if x != nil {
		return x.FileAge
	}
	return nil
}

func (x *LogConfig) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_debug
}

func (x *LogConfig) GetConstKv() []string {
	if x != nil {
		return x.ConstKv
	}
	return nil
}

func (x *LogConfig) GetDisableJsonFmt() bool {
	if x != nil {
		return x.DisableJsonFmt
	}
	return false
}

func (x *LogConfig) GetBeautyJsonFmt() bool {
	if x != nil {
		return x.BeautyJsonFmt
	}
	return false
}

var File_gt_conf_pb_gt_logger_pb_proto protoreflect.FileDescriptor

const file_gt_conf_pb_gt_logger_pb_proto_rawDesc = "" +
	"\n" +
	"\x1dgt-conf-pb/gt-logger-pb.proto\x12\bgtconfpb\x1a\x1egoogle/protobuf/duration.proto\"\xa4\x03\n" +
	"\tLogConfig\x12,\n" +
	"\x11disableFileWriter\x18\x01 \x01(\bR\x11disableFileWriter\x12$\n" +
	"\rdisableStdOut\x18\x02 \x01(\bR\rdisableStdOut\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12B\n" +
	"\frotationTime\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x00R\frotationTime\x88\x01\x01\x128\n" +
	"\afileAge\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x01R\afileAge\x88\x01\x01\x12.\n" +
	"\blogLevel\x18\x06 \x01(\x0e2\x12.gtconfpb.LogLevelR\blogLevel\x12\x18\n" +
	"\aconstKv\x18\a \x03(\tR\aconstKv\x12&\n" +
	"\x0edisableJsonFmt\x18\b \x01(\bR\x0edisableJsonFmt\x12$\n" +
	"\rbeautyJsonFmt\x18\t \x01(\bR\rbeautyJsonFmtB\x0f\n" +
	"\r_rotationTimeB\n" +
	"\n" +
	"\b_fileAge*?\n" +
	"\bLogLevel\x12\t\n" +
	"\x05debug\x10\x00\x12\b\n" +
	"\x04info\x10\x01\x12\b\n" +
	"\x04warn\x10\x02\x12\t\n" +
	"\x05error\x10\x03\x12\t\n" +
	"\x05fatal\x10\x04B;Z9github.com/DontBeProud/go-treasure/pb/gt-conf-pb;gtconfpbb\x06proto3"

var (
	file_gt_conf_pb_gt_logger_pb_proto_rawDescOnce sync.Once
	file_gt_conf_pb_gt_logger_pb_proto_rawDescData []byte
)

func file_gt_conf_pb_gt_logger_pb_proto_rawDescGZIP() []byte {
	file_gt_conf_pb_gt_logger_pb_proto_rawDescOnce.Do(func() {
		file_gt_conf_pb_gt_logger_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gt_logger_pb_proto_rawDesc), len(file_gt_conf_pb_gt_logger_pb_proto_rawDesc)))
	})
	return file_gt_conf_pb_gt_logger_pb_proto_rawDescData
}

var file_gt_conf_pb_gt_logger_pb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gt_conf_pb_gt_logger_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gt_conf_pb_gt_logger_pb_proto_goTypes = []any{
	(LogLevel)(0),               // 0: gtconfpb.LogLevel
	(*LogConfig)(nil),           // 1: gtconfpb.LogConfig
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_gt_conf_pb_gt_logger_pb_proto_depIdxs = []int32{
	2, // 0: gtconfpb.LogConfig.rotationTime:type_name -> google.protobuf.Duration
	2, // 1: gtconfpb.LogConfig.fileAge:type_name -> google.protobuf.Duration
	0, // 2: gtconfpb.LogConfig.logLevel:type_name -> gtconfpb.LogLevel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gt_conf_pb_gt_logger_pb_proto_init() }
func file_gt_conf_pb_gt_logger_pb_proto_init() {
	if File_gt_conf_pb_gt_logger_pb_proto != nil {
		return
	}
	file_gt_conf_pb_gt_logger_pb_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gt_logger_pb_proto_rawDesc), len(file_gt_conf_pb_gt_logger_pb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gt_conf_pb_gt_logger_pb_proto_goTypes,
		DependencyIndexes: file_gt_conf_pb_gt_logger_pb_proto_depIdxs,
		EnumInfos:         file_gt_conf_pb_gt_logger_pb_proto_enumTypes,
		MessageInfos:      file_gt_conf_pb_gt_logger_pb_proto_msgTypes,
	}.Build()
	File_gt_conf_pb_gt_logger_pb_proto = out.File
	file_gt_conf_pb_gt_logger_pb_proto_goTypes = nil
	file_gt_conf_pb_gt_logger_pb_proto_depIdxs = nil
}
