// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: gt-conf-pb/gt-sharding.proto

package gtconfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 时间分割(分库/分表)策略的分割级别
type ShardingTimeLevel int32

const (
	ShardingTimeLevel_Disabled  ShardingTimeLevel = 0  // 不使用基于时间分割的规则
	ShardingTimeLevel_Hour      ShardingTimeLevel = 1  // 小时
	ShardingTimeLevel_HalfDay   ShardingTimeLevel = 2  // 半天(每12个小时分割一次)
	ShardingTimeLevel_Day       ShardingTimeLevel = 3  // 天
	ShardingTimeLevel_Week      ShardingTimeLevel = 4  // 周(每周一为分割日)
	ShardingTimeLevel_HalfMonth ShardingTimeLevel = 5  // 半月(每个月的1号和16号位分割月)
	ShardingTimeLevel_Month     ShardingTimeLevel = 6  // 月
	ShardingTimeLevel_TwoMonth  ShardingTimeLevel = 7  // 2月
	ShardingTimeLevel_Quarter   ShardingTimeLevel = 8  // 季度
	ShardingTimeLevel_HalfYear  ShardingTimeLevel = 9  // 半年
	ShardingTimeLevel_Year      ShardingTimeLevel = 10 // 年
)

// Enum value maps for ShardingTimeLevel.
var (
	ShardingTimeLevel_name = map[int32]string{
		0:  "Disabled",
		1:  "Hour",
		2:  "HalfDay",
		3:  "Day",
		4:  "Week",
		5:  "HalfMonth",
		6:  "Month",
		7:  "TwoMonth",
		8:  "Quarter",
		9:  "HalfYear",
		10: "Year",
	}
	ShardingTimeLevel_value = map[string]int32{
		"Disabled":  0,
		"Hour":      1,
		"HalfDay":   2,
		"Day":       3,
		"Week":      4,
		"HalfMonth": 5,
		"Month":     6,
		"TwoMonth":  7,
		"Quarter":   8,
		"HalfYear":  9,
		"Year":      10,
	}
)

func (x ShardingTimeLevel) Enum() *ShardingTimeLevel {
	p := new(ShardingTimeLevel)
	*p = x
	return p
}

func (x ShardingTimeLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardingTimeLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_gt_conf_pb_gt_sharding_proto_enumTypes[0].Descriptor()
}

func (ShardingTimeLevel) Type() protoreflect.EnumType {
	return &file_gt_conf_pb_gt_sharding_proto_enumTypes[0]
}

func (x ShardingTimeLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardingTimeLevel.Descriptor instead.
func (ShardingTimeLevel) EnumDescriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_sharding_proto_rawDescGZIP(), []int{0}
}

// 根命名规则
type ShardingRootConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConstPrefix   string                 `protobuf:"bytes,1,opt,name=constPrefix,proto3" json:"constPrefix,omitempty"` // 固定前缀
	ConstSuffix   string                 `protobuf:"bytes,2,opt,name=constSuffix,proto3" json:"constSuffix,omitempty"` // 固定后缀
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardingRootConfig) Reset() {
	*x = ShardingRootConfig{}
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingRootConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingRootConfig) ProtoMessage() {}

func (x *ShardingRootConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingRootConfig.ProtoReflect.Descriptor instead.
func (*ShardingRootConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_sharding_proto_rawDescGZIP(), []int{0}
}

func (x *ShardingRootConfig) GetConstPrefix() string {
	if x != nil {
		return x.ConstPrefix
	}
	return ""
}

func (x *ShardingRootConfig) GetConstSuffix() string {
	if x != nil {
		return x.ConstSuffix
	}
	return ""
}

// 时间分割(分库/分表)策略配置的proto
type ShardingWithTimeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TimeLevel          ShardingTimeLevel      `protobuf:"varint,1,opt,name=timeLevel,proto3,enum=gtconfpb.ShardingTimeLevel" json:"timeLevel,omitempty"` // 时间分割级别
	SplitCharacter     string                 `protobuf:"bytes,2,opt,name=splitCharacter,proto3" json:"splitCharacter,omitempty"`                        // 分割字符
	TimeSplitCharacter string                 `protobuf:"bytes,3,opt,name=timeSplitCharacter,proto3" json:"timeSplitCharacter,omitempty"`                // 各时间成员之间的分割字符
	EarliestValidTime  uint64                 `protobuf:"varint,4,opt,name=earliestValidTime,proto3" json:"earliestValidTime,omitempty"`                 // 最早的有效时间(分库分表的业务场景一般需要设置一个最早有效时间, 否则在查询等场景中可能出现表未创建的情况)
	PrefixMode         bool                   `protobuf:"varint,5,opt,name=prefixMode,proto3" json:"prefixMode,omitempty"`                               // 时间信息是否置于命名前缀(默认位false，即采用raw - date的格式)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShardingWithTimeConfig) Reset() {
	*x = ShardingWithTimeConfig{}
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingWithTimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingWithTimeConfig) ProtoMessage() {}

func (x *ShardingWithTimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingWithTimeConfig.ProtoReflect.Descriptor instead.
func (*ShardingWithTimeConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_sharding_proto_rawDescGZIP(), []int{1}
}

func (x *ShardingWithTimeConfig) GetTimeLevel() ShardingTimeLevel {
	if x != nil {
		return x.TimeLevel
	}
	return ShardingTimeLevel_Disabled
}

func (x *ShardingWithTimeConfig) GetSplitCharacter() string {
	if x != nil {
		return x.SplitCharacter
	}
	return ""
}

func (x *ShardingWithTimeConfig) GetTimeSplitCharacter() string {
	if x != nil {
		return x.TimeSplitCharacter
	}
	return ""
}

func (x *ShardingWithTimeConfig) GetEarliestValidTime() uint64 {
	if x != nil {
		return x.EarliestValidTime
	}
	return 0
}

func (x *ShardingWithTimeConfig) GetPrefixMode() bool {
	if x != nil {
		return x.PrefixMode
	}
	return false
}

// ShardingRuleWithGroupConfig 基于分组的分割规则配置
type ShardingRuleWithGroupConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GroupSize             uint64                 `protobuf:"varint,1,opt,name=groupSize,proto3" json:"groupSize,omitempty"`                         // 分组数量(实际使用的过程中，建议使用2的N次方)
	SplitCharacter        string                 `protobuf:"bytes,2,opt,name=splitCharacter,proto3" json:"splitCharacter,omitempty"`                // 分割字符 raw + SplitCharacter + group
	PrefixMode            bool                   `protobuf:"varint,3,opt,name=prefixMode,proto3" json:"prefixMode,omitempty"`                       // 分组信息是否置于命名前缀(默认位false，即采用raw - group的格式)
	IndexIncreaseFromZero bool                   `protobuf:"varint,4,opt,name=indexIncreaseFromZero,proto3" json:"indexIncreaseFromZero,omitempty"` // 分组序号是否从0增长. true: 0.1.2.3....  false: 1.2.3.4....
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShardingRuleWithGroupConfig) Reset() {
	*x = ShardingRuleWithGroupConfig{}
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingRuleWithGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingRuleWithGroupConfig) ProtoMessage() {}

func (x *ShardingRuleWithGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gt_conf_pb_gt_sharding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingRuleWithGroupConfig.ProtoReflect.Descriptor instead.
func (*ShardingRuleWithGroupConfig) Descriptor() ([]byte, []int) {
	return file_gt_conf_pb_gt_sharding_proto_rawDescGZIP(), []int{2}
}

func (x *ShardingRuleWithGroupConfig) GetGroupSize() uint64 {
	if x != nil {
		return x.GroupSize
	}
	return 0
}

func (x *ShardingRuleWithGroupConfig) GetSplitCharacter() string {
	if x != nil {
		return x.SplitCharacter
	}
	return ""
}

func (x *ShardingRuleWithGroupConfig) GetPrefixMode() bool {
	if x != nil {
		return x.PrefixMode
	}
	return false
}

func (x *ShardingRuleWithGroupConfig) GetIndexIncreaseFromZero() bool {
	if x != nil {
		return x.IndexIncreaseFromZero
	}
	return false
}

var File_gt_conf_pb_gt_sharding_proto protoreflect.FileDescriptor

const file_gt_conf_pb_gt_sharding_proto_rawDesc = "" +
	"\n" +
	"\x1cgt-conf-pb/gt-sharding.proto\x12\bgtconfpb\"X\n" +
	"\x12ShardingRootConfig\x12 \n" +
	"\vconstPrefix\x18\x01 \x01(\tR\vconstPrefix\x12 \n" +
	"\vconstSuffix\x18\x02 \x01(\tR\vconstSuffix\"\xf9\x01\n" +
	"\x16ShardingWithTimeConfig\x129\n" +
	"\ttimeLevel\x18\x01 \x01(\x0e2\x1b.gtconfpb.ShardingTimeLevelR\ttimeLevel\x12&\n" +
	"\x0esplitCharacter\x18\x02 \x01(\tR\x0esplitCharacter\x12.\n" +
	"\x12timeSplitCharacter\x18\x03 \x01(\tR\x12timeSplitCharacter\x12,\n" +
	"\x11earliestValidTime\x18\x04 \x01(\x04R\x11earliestValidTime\x12\x1e\n" +
	"\n" +
	"prefixMode\x18\x05 \x01(\bR\n" +
	"prefixMode\"\xb9\x01\n" +
	"\x1bShardingRuleWithGroupConfig\x12\x1c\n" +
	"\tgroupSize\x18\x01 \x01(\x04R\tgroupSize\x12&\n" +
	"\x0esplitCharacter\x18\x02 \x01(\tR\x0esplitCharacter\x12\x1e\n" +
	"\n" +
	"prefixMode\x18\x03 \x01(\bR\n" +
	"prefixMode\x124\n" +
	"\x15indexIncreaseFromZero\x18\x04 \x01(\bR\x15indexIncreaseFromZero*\x98\x01\n" +
	"\x11ShardingTimeLevel\x12\f\n" +
	"\bDisabled\x10\x00\x12\b\n" +
	"\x04Hour\x10\x01\x12\v\n" +
	"\aHalfDay\x10\x02\x12\a\n" +
	"\x03Day\x10\x03\x12\b\n" +
	"\x04Week\x10\x04\x12\r\n" +
	"\tHalfMonth\x10\x05\x12\t\n" +
	"\x05Month\x10\x06\x12\f\n" +
	"\bTwoMonth\x10\a\x12\v\n" +
	"\aQuarter\x10\b\x12\f\n" +
	"\bHalfYear\x10\t\x12\b\n" +
	"\x04Year\x10\n" +
	"B;Z9github.com/DontBeProud/go-treasure/pb/gt-conf-pb;gtconfpbb\x06proto3"

var (
	file_gt_conf_pb_gt_sharding_proto_rawDescOnce sync.Once
	file_gt_conf_pb_gt_sharding_proto_rawDescData []byte
)

func file_gt_conf_pb_gt_sharding_proto_rawDescGZIP() []byte {
	file_gt_conf_pb_gt_sharding_proto_rawDescOnce.Do(func() {
		file_gt_conf_pb_gt_sharding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gt_sharding_proto_rawDesc), len(file_gt_conf_pb_gt_sharding_proto_rawDesc)))
	})
	return file_gt_conf_pb_gt_sharding_proto_rawDescData
}

var file_gt_conf_pb_gt_sharding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gt_conf_pb_gt_sharding_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gt_conf_pb_gt_sharding_proto_goTypes = []any{
	(ShardingTimeLevel)(0),              // 0: gtconfpb.ShardingTimeLevel
	(*ShardingRootConfig)(nil),          // 1: gtconfpb.ShardingRootConfig
	(*ShardingWithTimeConfig)(nil),      // 2: gtconfpb.ShardingWithTimeConfig
	(*ShardingRuleWithGroupConfig)(nil), // 3: gtconfpb.ShardingRuleWithGroupConfig
}
var file_gt_conf_pb_gt_sharding_proto_depIdxs = []int32{
	0, // 0: gtconfpb.ShardingWithTimeConfig.timeLevel:type_name -> gtconfpb.ShardingTimeLevel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gt_conf_pb_gt_sharding_proto_init() }
func file_gt_conf_pb_gt_sharding_proto_init() {
	if File_gt_conf_pb_gt_sharding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gt_conf_pb_gt_sharding_proto_rawDesc), len(file_gt_conf_pb_gt_sharding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gt_conf_pb_gt_sharding_proto_goTypes,
		DependencyIndexes: file_gt_conf_pb_gt_sharding_proto_depIdxs,
		EnumInfos:         file_gt_conf_pb_gt_sharding_proto_enumTypes,
		MessageInfos:      file_gt_conf_pb_gt_sharding_proto_msgTypes,
	}.Build()
	File_gt_conf_pb_gt_sharding_proto = out.File
	file_gt_conf_pb_gt_sharding_proto_goTypes = nil
	file_gt_conf_pb_gt_sharding_proto_depIdxs = nil
}
